// Generated by CoffeeScript 1.7.1
(function() {
  var SuperpooperView;

  SuperpooperView = require('./superpooper-view');

  module.exports = {
    activate: function() {
      return atom.workspaceView.command("superpooper:claim", (function(_this) {
        return function() {
          return _this.claim();
        };
      })(this));
    },
    claim: function() {
      var editor;
      editor = atom.workspace.activePaneItem;
      return editor.insertText('Superpooper the atom package! Someday you will lead millions! Willingly or as slaves');
    }
  };

}).call(this);
